# Copyright (c) 2019 Abhishek Thakur(@abhiTronix) <abhi.una12@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Project information
site_name: VidGear
site_url: https://abhitronix.github.io/vidgear/
site_author: Abhishek Thakur
site_description: >-
  A High-Performance Video-Processing Python Framework for building complex real-time media applications. ðŸ”¥

# Repository
repo_name: abhiTronix/vidgear
repo_url: https://github.com/abhiTronix/vidgear
edit_uri: edit/testing/docs/

# Copyright
copyright: Copyright &copy; 2019 Abhishek Thakur(@abhiTronix)

# Configuration
theme:
  name: material
  custom_dir: docs/overrides

  # Default values, taken from mkdocs_theme.yml
  features:
    - announce.dismiss
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.footnote.tooltips
    - content.action.view
    - content.action.edit
    - content.tooltips
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/weather-hazy
        name: Switch to light mode
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: dark purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to system mode
  font:
    text: Source Sans 3
    code: Fira Code
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/light-bulb-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  logo: assets/images/logo.svg
  favicon: assets/images/favicon-32.png
  static_templates:
    - 404.html

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - minify:
      minify_html: true
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: false
            show_root_toc_entry: false
            show_source: true
            heading_level: 3
  - exclude:
      glob:
        - overrides/assets/README.md

# Hooks
hooks:
  - docs/overrides/hooks/js_hook.py

# Logging
validation:
  unrecognized_links: ignore

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/abhiTronix
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/vidgear/community
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/abhishek-singh-thakur-a37845a5
    - icon: fontawesome/brands/dev
      link: https://dev.to/abhitronix
  version:
    provider: mike
    default: latest
  analytics: # Google analytics
    provider: google
    property: G-XMZCQ3KBNJ
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

extra_css:
  - assets/stylesheets/custom.css

extra_javascript:
  - assets/javascripts/extra.js

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - tables
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: abhiTronix
      repo: vidgear
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home:
      - Overview: index.md
      - Installation:
          - Installation Overview: installation.md
          - Install using pip: installation/pip_install.md
          - Install from source: installation/source_install.md
      - Switching from OpenCV: switch_from_cv.md
      - Contribution Guidelines:
          - Contribution Overview: contribution.md
          - Submitting an Issue Guidelines: contribution/issue.md
          - Submitting Pull Request(PR) Guidelines: contribution/PR.md
      - Release Notes: changelog.md
      - License: license.md
  - Gears:
      - Introduction: gears.md
      - CamGear:
          - Overview: gears/camgear/overview.md
          - Usage Examples: gears/camgear/usage.md
          - Parameters: gears/camgear/params.md
          - Bonus:
              - Source Tweak Parameters: gears/camgear/advanced/source_params.md
              - CamGear API References: bonus/reference/camgear.md
              - Bonus Examples: help/camgear_ex.md
              - FAQs: help/camgear_faqs.md
      - PiGear:
          - Overview: gears/pigear/overview.md
          - Usage Examples: gears/pigear/usage.md
          - Parameters: gears/pigear/params.md
          - Bonus:
              - PiGear API References: bonus/reference/pigear.md
              - Bonus Examples: help/pigear_ex.md
              - FAQs: help/pigear_faqs.md
      - VideoGear:
          - Overview: gears/videogear/overview.md
          - Usage Examples: gears/videogear/usage.md
          - Parameters: gears/videogear/params.md
          - Bonus:
              - VideoGear API References: bonus/reference/videogear.md
              - Bonus Examples: help/videogear_ex.md
              - FAQs: help/videogear_faqs.md
      - ScreenGear:
          - Overview: gears/screengear/overview.md
          - Usage Examples: gears/screengear/usage.md
          - Parameters: gears/screengear/params.md
          - Bonus:
              - ScreenGear API References: bonus/reference/screengear.md
              - Bonus Examples: help/screengear_ex.md
              - FAQs: help/screengear_faqs.md
      - WriteGear:
          - Introduction: gears/writegear/introduction.md
          - Compression Mode:
              - Overview: gears/writegear/compression/overview.md
              - Usage Examples: gears/writegear/compression/usage.md
              - Advanced:
                  - Custom FFmpeg Commands: gears/writegear/compression/advanced/cciw.md
                  - FFmpeg Installation: gears/writegear/compression/advanced/ffmpeg_install.md
              - Parameters: gears/writegear/compression/params.md
          - Non-Compression Mode:
              - Overview: gears/writegear/non_compression/overview.md
              - Usage Examples: gears/writegear/non_compression/usage.md
              - Parameters: gears/writegear/non_compression/params.md
          - Bonus:
              - WriteGear API References: bonus/reference/writegear.md
              - Bonus Examples: help/writegear_ex.md
              - FAQs: help/writegear_faqs.md
      - StreamGear:
          - Introduction: gears/streamgear/introduction.md
          - Single-Source Mode:
              - Overview: gears/streamgear/ssm/overview.md
              - Usage Examples: gears/streamgear/ssm/usage.md
          - Real-time Frames Mode:
              - Overview: gears/streamgear/rtfm/overview.md
              - Usage Examples: gears/streamgear/rtfm/usage.md
          - Parameters: gears/streamgear/params.md
          - Bonus:
              - StreamGear API References: bonus/reference/streamgear.md
              - FFmpeg Installation: gears/streamgear/ffmpeg_install.md
              - Bonus Examples: help/streamgear_ex.md
              - FAQs: help/streamgear_faqs.md
      - NetGear:
          - Overview: gears/netgear/overview.md
          - Usage Examples: gears/netgear/usage.md
          - Advanced Usages:
              - Multi-Servers Mode: gears/netgear/advanced/multi_server.md
              - Multi-Clients Mode: gears/netgear/advanced/multi_client.md
              - Bidirectional Mode: gears/netgear/advanced/bidirectional_mode.md
              - SSH Tunneling Mode: gears/netgear/advanced/ssh_tunnel.md
              - Secure Mode: gears/netgear/advanced/secure_mode.md
              - Frame Compression: gears/netgear/advanced/compression.md
          - Parameters: gears/netgear/params.md
          - Bonus:
              - NetGear API References: bonus/reference/netgear.md
              - Bonus Examples: help/netgear_ex.md
              - FAQs: help/netgear_faqs.md
      - WebGear:
          - Overview: gears/webgear/overview.md
          - Usage Examples: gears/webgear/usage.md
          - Advanced Usages: gears/webgear/advanced.md
          - Parameters: gears/webgear/params.md
          - Bonus:
              - WebGear API References: bonus/reference/webgear.md
              - Bonus Examples: help/webgear_ex.md
              - FAQs: help/webgear_faqs.md
      - WebGear_RTC:
          - Overview: gears/webgear_rtc/overview.md
          - Usage Examples: gears/webgear_rtc/usage.md
          - Advanced Usages: gears/webgear_rtc/advanced.md
          - Parameters: gears/webgear_rtc/params.md
          - Bonus:
              - WebGear_RTC API References: bonus/reference/webgear_rtc.md
              - Bonus Examples: help/webgear_rtc_ex.md
              - FAQs: help/webgear_rtc_faqs.md
      - NetGear_Async:
          - Overview: gears/netgear_async/overview.md
          - Usage Examples: gears/netgear_async/usage.md
          - Advanced Usages:
              - Bidirectional Mode: gears/netgear_async/advanced/bidirectional_mode.md
          - Parameters: gears/netgear_async/params.md
          - Bonus:
              - NetGear_Async API References: bonus/reference/netgear_async.md
              - Bonus Examples: help/netgear_async_ex.md
              - FAQs: help/netgear_async_faqs.md
      - Stabilizer Class:
          - Overview: gears/stabilizer/overview.md
          - Usage Examples: gears/stabilizer/usage.md
          - Parameters: gears/stabilizer/params.md
          - Bonus:
              - API References: bonus/reference/stabilizer.md
              - Bonus Examples: help/stabilizer_ex.md
              - FAQs: help/stabilizer_faqs.md
  - References:
      - API References:
          - vidgear.gears:
              - CamGear API: bonus/reference/camgear.md
              - PiGear API: bonus/reference/pigear.md
              - VideoGear API: bonus/reference/videogear.md
              - ScreenGear API: bonus/reference/screengear.md
              - WriteGear API: bonus/reference/writegear.md
              - StreamGear API: bonus/reference/streamgear.md
              - NetGear API: bonus/reference/netgear.md
              - Stabilizer Class: bonus/reference/stabilizer.md
              - Helper Methods: bonus/reference/helper.md
          - vidgear.gears.asyncio:
              - WebGear API: bonus/reference/webgear.md
              - WebGear_RTC API: bonus/reference/webgear_rtc.md
              - NetGear_Async API: bonus/reference/netgear_async.md
              - Helper Methods: bonus/reference/helper_async.md
      - Colorspace Manipulation: bonus/colorspace_manipulation.md
      - Threaded Queue Mode: bonus/TQM.md
      - VidGear Docker Streamer: bonus/docker_example.md
  - Help:
      - Help VidGear 'n' Get Help:
          - Helping VidGear: help.md
          - Getting Help: help/get_help.md
      - Frequently Asked Questions:
          - General FAQs: help/general_faqs.md
          - CamGear FAQs: help/camgear_faqs.md
          - PiGear FAQs: help/pigear_faqs.md
          - VideoGear FAQs: help/videogear_faqs.md
          - ScreenGear FAQs: help/screengear_faqs.md
          - WriteGear FAQs: help/writegear_faqs.md
          - StreamGear FAQs: help/streamgear_faqs.md
          - NetGear FAQs: help/netgear_faqs.md
          - WebGear FAQs: help/webgear_faqs.md
          - WebGear_RTC FAQs: help/webgear_rtc_faqs.md
          - NetGear_Async FAQs: help/netgear_async_faqs.md
          - Stabilizer Class FAQs: help/stabilizer_faqs.md
      - Bonus Examples:
          - CamGear Examples: help/camgear_ex.md
          - PiGear Examples: help/pigear_ex.md
          - VideoGear Examples: help/videogear_ex.md
          - ScreenGear Examples: help/screengear_ex.md
          - WriteGear Examples: help/writegear_ex.md
          - StreamGear Examples: help/streamgear_ex.md
          - NetGear Examples: help/netgear_ex.md
          - WebGear Examples: help/webgear_ex.md
          - WebGear_RTC Examples: help/webgear_rtc_ex.md
          - NetGear_Async Examples: help/netgear_async_ex.md
          - Stabilizer Class Examples: help/stabilizer_ex.md
